services:
  - type: web
    name: ewidencja-czasu
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "YOUR_DOMAIN"
      - key: SECRET_KEY
        generateValue: true
